version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  # Zookeeper microservice
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "./app/zookeeper_service:/opt/bitnami/zookeeper/app"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
      
  # Kafka microservice
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "./app/kafka_service:/opt/bitnami/kafka/app"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-tier